package network.reticulum.lxmf.conformance

import kotlinx.coroutines.runBlocking
import network.reticulum.Reticulum
import network.reticulum.common.DestinationDirection
import network.reticulum.common.DestinationType
import network.reticulum.common.toHexString
import network.reticulum.destination.Destination
import network.reticulum.identity.Identity
import network.reticulum.interfaces.Interface
import network.reticulum.interfaces.tcp.TCPClientInterface
import network.reticulum.interfaces.tcp.TCPServerInterface
import network.reticulum.interfaces.toRef
import network.reticulum.lxmf.DeliveryMethod
import network.reticulum.lxmf.LXMRouter
import network.reticulum.lxmf.LXMessage
import network.reticulum.lxmf.MessageState
import network.reticulum.transport.Transport
import org.json.JSONArray
import org.json.JSONObject
import java.io.BufferedReader
import java.io.File
import java.io.InputStreamReader
import java.net.ServerSocket
import java.nio.file.Files
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.locks.ReentrantLock
import kotlin.concurrent.withLock
import kotlin.system.exitProcess

/**
 * LXMF Kotlin conformance bridge.
 *
 * JSON-RPC over stdio, one object per line. Mirrors the python reference
 * at lxmf-conformance/reference/lxmf_python.py command-for-command. See
 * the README in the lxmf-conformance repo for the contract.
 *
 * Wire protocol:
 *   - On startup, prints exactly "READY" on stdout, then enters loop.
 *   - Reads JSON requests from stdin, one per line:
 *       {"id": "req-N", "command": "...", "params": {...}}
 *   - Writes JSON responses on stdout, one per line:
 *       {"id": "req-N", "success": true, "result": {...}}
 *       {"id": "req-N", "success": false, "error": "..."}
 *
 * stderr is left for log noise; stdout is sacred — the test harness
 * filters non-JSON lines on stdout but it's still fragile, so we
 * suppress slf4j-simple at WARN.
 */

// ----------------------------------------------------------------------
// Bridge state. Single-instance per process, mirroring lxmf_python.py.
// ----------------------------------------------------------------------

private object BridgeState {
    @Volatile var reticulum: Reticulum? = null
    @Volatile var router: LXMRouter? = null
    @Volatile var identity: Identity? = null
    @Volatile var deliveryDestination: Destination? = null
    @Volatile var configDir: String? = null
    @Volatile var storagePath: String? = null

    // True only when storagePath was auto-generated by lxmf_init because
    // the caller didn't supply one. lxmf_shutdown's recursive-delete must
    // skip caller-supplied paths so a fixture that reuses storage across
    // multiple trios doesn't get its data wiped.
    @Volatile var storagePathAutoCreated: Boolean = false

    // Inbound message queue. Append-only with monotonic seq.
    val inbox = mutableListOf<JSONObject>()
    val inboxLock = ReentrantLock()
    @Volatile var inboxSeq = 0

    // Outbound message state map: hex -> state name. Updated by the
    // per-message deliveryCallback / failedCallback closures plus a
    // synchronous post-handleOutbound write in each cmdLxmf_send_*.
    val outboundState = ConcurrentHashMap<String, String>()

    // Live LXMessage references keyed by message hash hex. Used by
    // cmdLxmfGetMessageState to read the *current* state from the
    // message itself. Required because LXMessage.deliveryCallback only
    // fires on the terminal transitions the router cares about
    // (DELIVERED for opportunistic, SENT for propagated): intermediate
    // transitions like opportunistic OUTBOUND→SENT (no proof yet) or
    // propagated OUTBOUND→SENDING (link established, transfer in flight)
    // never fire a callback, so outboundState alone reports stale
    // 'outbound' for messages that have actually advanced.
    val outboundMessages = ConcurrentHashMap<String, LXMessage>()

    // Set true at the top of cmdLxmfShutdown so any callbacks the router
    // schedules during teardown can't repopulate `outboundState` /
    // `inbox` after we've cleared them. The router's own callbacks may
    // fire on background threads after `router.stop()` returns.
    @Volatile var shuttingDown: Boolean = false

    // Started TCP interfaces (for shutdown).
    val interfaces = mutableListOf<Interface>()
}

// ----------------------------------------------------------------------
// Helpers
// ----------------------------------------------------------------------

private fun stateToString(state: MessageState?): String =
    when (state) {
        MessageState.GENERATING -> "generating"
        MessageState.OUTBOUND -> "outbound"
        MessageState.SENDING -> "sending"
        MessageState.SENT -> "sent"
        MessageState.DELIVERED -> "delivered"
        MessageState.FAILED -> "failed"
        MessageState.REJECTED -> "failed"
        MessageState.CANCELLED -> "failed"
        null -> "unknown"
    }

private fun methodToString(method: DeliveryMethod?): String =
    when (method) {
        DeliveryMethod.OPPORTUNISTIC -> "opportunistic"
        DeliveryMethod.DIRECT -> "direct"
        DeliveryMethod.PROPAGATED -> "propagated"
        else -> "unknown"
    }

/**
 * Pick an OS-assigned ephemeral port by binding then immediately closing
 * a probe socket.
 *
 * There is a small TOCTOU race here: between this function returning and
 * `TCPServerInterface.start()` actually binding to the returned port,
 * another process could in principle claim it. In practice this is a
 * non-issue for the conformance bridge:
 *
 *   - GitHub Actions runners isolate jobs onto separate VMs, so parallel
 *     CI jobs cannot race for the same loopback port.
 *   - Within a single bridge process this function is called serially,
 *     <1ms before TCPServerInterface binds — the kernel doesn't reassign
 *     a freshly-released ephemeral port that fast.
 *
 * If the upstream TCPServerInterface API ever gains support for reading
 * back its actual bound port after `start()` (analogous to ServerSocket's
 * `localPort` once `bind()` returns), we could pass `bindPort = 0` and
 * read the assignment back, eliminating the race entirely. Until then,
 * this is the cheapest workable approximation.
 */
private fun allocateFreePort(): Int {
    val s = ServerSocket()
    return try {
        s.bind(java.net.InetSocketAddress("127.0.0.1", 0))
        s.localPort
    } finally {
        s.close()
    }
}

private fun ensureRouter(name: String): LXMRouter =
    BridgeState.router
        ?: throw IllegalStateException("lxmf_init must be called before $name")

/** Terminal outbound states — once observed, never overwrite. */
private val TERMINAL_OUTBOUND_STATES = setOf("delivered", "failed")

/**
 * Record an outbound message state without downgrading a terminal one.
 *
 * Three writers race on `outboundState[hash]`: the per-message
 * `deliveryCallback` (any thread the router schedules its callbacks on),
 * the `failedCallback` (same), and the synchronous post-handleOutbound
 * write in each `cmdLxmf_send_*`. If a fast OPPORTUNISTIC delivery
 * completes its callback chain BEFORE the synchronous write reads
 * `message.state`, the synchronous write would overwrite a terminal
 * "delivered" with the now-stale "sending". Use compute() to keep
 * the latest terminal state once we see one.
 *
 * Also no-ops once `BridgeState.shuttingDown` is set so late-firing
 * callbacks don't repopulate the map after `cmdLxmfShutdown` cleared it.
 */
private fun recordOutboundState(hashHex: String, newState: String) {
    if (BridgeState.shuttingDown) return
    BridgeState.outboundState.compute(hashHex) { _, existing ->
        if (existing in TERMINAL_OUTBOUND_STATES) existing else newState
    }
}

// ----------------------------------------------------------------------
// LXMF field codec
// ----------------------------------------------------------------------
//
// LXMF `fields` is a `Map<Int, Any>` whose leaf values can be ByteArray,
// String, Int/Long, Boolean, or nested Lists/Maps; the wire format is
// msgpack and ByteArray vs String are *distinct* msgpack types. JSON-RPC
// can't carry bytes natively so the bridge contract uses tagged objects:
//   - {"bytes": "<hex>"}
//   - {"str": "..."}
//   - {"int": 123}
//   - {"bool": true}
//   - JSON arrays for lists
//   - bare JSON primitives pass through
//
// The explicit "bytes" tag is load-bearing for FIELD_FILE_ATTACHMENTS
// (id 0x05): each attachment is `[filename_str, data_bytes]` and without
// the tag we'd lose the bytes-vs-string distinction round-tripping
// through JSON. Mirrors reference/lxmf_python.py exactly.

private fun decodeFieldValue(value: Any?): Any? {
    if (value == null || value == JSONObject.NULL) return null
    return when (value) {
        is JSONObject -> when {
            value.has("bytes") -> hexToBytes(value.getString("bytes"))
            value.has("str") -> value.getString("str")
            value.has("int") -> value.getLong("int")
            value.has("bool") -> value.getBoolean("bool")
            else -> {
                // Bare object — treat as nested map with string keys.
                val out = mutableMapOf<String, Any?>()
                for (k in value.keys()) out[k] = decodeFieldValue(value.get(k))
                out
            }
        }
        is JSONArray -> {
            val out = mutableListOf<Any?>()
            for (i in 0 until value.length()) out.add(decodeFieldValue(value.get(i)))
            out
        }
        else -> value
    }
}

private fun decodeFieldsParam(params: JSONObject): MutableMap<Int, Any> {
    val raw = params.optJSONObject("fields") ?: return mutableMapOf()
    val out = mutableMapOf<Int, Any>()
    for (k in raw.keys()) {
        val decoded = decodeFieldValue(raw.get(k))
            ?: continue // null leaves don't survive into LXMF anyway
        // LXMF field IDs are decimal strings on the JSON-RPC wire. Surface
        // a clear validation error rather than leaking NumberFormatException
        // up through handleRequest, which would otherwise present as a raw
        // JVM stack trace to the test harness on a malformed payload.
        val id = k.toIntOrNull()
            ?: throw IllegalArgumentException(
                "fields key '$k' is not a decimal integer (LXMF field IDs are 0..255)",
            )
        out[id] = decoded
    }
    return out
}

// Encoder: convert ByteArray -> hex so the value is JSON-safe. Mirrors
// the python bridge's _encode_field_value_for_inbox; the test suite
// asserts on hex strings (not the tagged form) when reading the inbox.
private fun encodeFieldValueForInbox(value: Any?): Any? {
    return when (value) {
        null -> JSONObject.NULL
        is ByteArray -> value.toHexString()
        is List<*> -> JSONArray().also { arr ->
            for (item in value) arr.put(encodeFieldValueForInbox(item))
        }
        is Map<*, *> -> JSONObject().also { obj ->
            for ((k, v) in value) obj.put(k.toString(), encodeFieldValueForInbox(v))
        }
        is Long, is Int, is Double, is Float, is Boolean, is String -> value
        // Anything else: stringify to keep JSON valid; loud failure is
        // better than silently dropping the value.
        else -> value.toString()
    }
}

// Note on key coercion: LXMF top-level field IDs are Int (0..255),
// rendered as decimal-string keys on the JSON wire ("5" for
// FIELD_FILE_ATTACHMENTS, etc.) — that's the spec contract this codec
// implements. Nested maps with non-string keys (Int, ByteArray) get
// stringified via k.toString() and DO NOT round-trip back to their
// original key type on the receive side. None of the LXMF fields the
// conformance suite exercises today have nested non-string keys, but
// any future test that uses one will need explicit handling here.
private fun encodeMessageFields(message: LXMessage): JSONObject {
    val out = JSONObject()
    for ((k, v) in message.fields) {
        out.put(k.toString(), encodeFieldValueForInbox(v))
    }
    return out
}

// ----------------------------------------------------------------------
// Command handlers
// ----------------------------------------------------------------------

private fun cmdLxmfInit(params: JSONObject): JSONObject {
    if (BridgeState.router != null) {
        throw IllegalStateException(
            "lxmf_init has already been called on this bridge process. " +
                "Spawn a separate bridge subprocess for each LXMF node."
        )
    }

    // Reset shuttingDown — `cmdLxmfShutdown` sets it true to gate late
    // callbacks from repopulating cleared collections, but it stays true
    // forever otherwise. If a caller invokes `lxmf_init` again after
    // `lxmf_shutdown` (even though the contract is one-shot per process,
    // we don't want a stale flag to silently no-op every callback that
    // checks it). The router-null guard above protects against the
    // intended-one-shot violation; this just makes the state clean if
    // it does happen.
    BridgeState.shuttingDown = false

    val callerStoragePath = params.optString("storage_path", "")
    val storagePathAutoCreated = callerStoragePath.isEmpty()
    val storagePath = if (storagePathAutoCreated) {
        Files.createTempDirectory("lxmf_conf_storage_").toAbsolutePath().toString()
    } else {
        callerStoragePath
    }
    val configDir = Files.createTempDirectory("lxmf_conf_rns_").toAbsolutePath().toString()
    val displayName = params.optString("display_name", "lxmf-conformance-peer-kt")

    // Write a minimal Reticulum config so RNS doesn't auto-generate a
    // share_instance / LocalServerInterface that would collide between
    // bridges in the same test.
    val configFile = File(configDir, "config")
    configFile.writeText(
        """
        |[reticulum]
        |  enable_transport = No
        |  share_instance = No
        |  respond_to_probes = No
        |
        |[interfaces]
        |
        """.trimMargin()
    )

    // Reticulum.start in reticulum-kt uses configDir to load identity etc.
    val rns = Reticulum.start(
        configDir = configDir,
        enableTransport = false,
        shareInstance = false,
    )

    // From here on, anything that throws must call Reticulum.stop() so we
    // don't leak the running RNS instance across bridge restarts. Lxmf_init
    // is idempotent at the contract level (one bridge process = one router)
    // but a partial init that left RNS running would prevent subsequent
    // tests in the same harness from re-establishing.
    val router: LXMRouter
    val deliveryDest: Destination
    val identity: Identity
    try {
        // Fresh identity per bridge process. Matches python reference.
        identity = Identity.create()
        router = LXMRouter(identity = identity, storagePath = storagePath)

        deliveryDest = router.registerDeliveryIdentity(identity, displayName = displayName)

        router.registerDeliveryCallback { message ->
            // Drop late callbacks that fire on background threads after
            // cmdLxmfShutdown cleared the inbox. Otherwise they re-add
            // the entry and the next test sees stale state.
            if (BridgeState.shuttingDown) return@registerDeliveryCallback
            val entry = JSONObject()
            entry.put("message_hash", message.hash?.toHexString() ?: "")
            entry.put("source_hash", message.sourceHash.toHexString())
            entry.put("destination_hash", message.destinationHash.toHexString())
            entry.put("title", message.title)
            entry.put("content", message.content)
            entry.put("method", methodToString(message.method))
            entry.put("ack_status", "received")
            entry.put("received_at_ms", System.currentTimeMillis())
            entry.put("fields", encodeMessageFields(message))
            // Increment seq AND add to inbox under a single lock acquisition.
            // Splitting them across two `withLock` blocks lets a poll between
            // the two release `last_seq=N` (already incremented) without the
            // entry seq=N in inbox — the next poll advances `since_seq` past
            // it and the entry is silently dropped.
            BridgeState.inboxLock.withLock {
                BridgeState.inboxSeq += 1
                entry.put("seq", BridgeState.inboxSeq)
                BridgeState.inbox.add(entry)
            }
        }

        router.start()
    } catch (t: Throwable) {
        runCatching { Reticulum.stop() }
        // configDir is always auto-created above; storagePath only when
        // the caller didn't supply one. Skip caller-supplied paths so a
        // retry path can't nuke their fixtures. Best-effort — log nothing
        // because we're about to rethrow and the caller's stack trace
        // is what matters.
        runCatching { File(configDir).deleteRecursively() }
        if (storagePathAutoCreated) {
            runCatching { File(storagePath).deleteRecursively() }
        }
        throw t
    }

    BridgeState.reticulum = rns
    BridgeState.router = router
    BridgeState.identity = identity
    BridgeState.deliveryDestination = deliveryDest
    BridgeState.configDir = configDir
    BridgeState.storagePath = storagePath
    BridgeState.storagePathAutoCreated = storagePathAutoCreated

    val result = JSONObject()
    result.put("identity_hash", identity.hash.toHexString())
    result.put("delivery_destination_hash", deliveryDest.hash.toHexString())
    result.put("config_dir", configDir)
    result.put("storage_path", storagePath)
    return result
}

private fun cmdLxmfAddTcpServerInterface(params: JSONObject): JSONObject {
    ensureRouter("lxmf_add_tcp_server_interface")
    val bindPort = params.optInt("bind_port", 0).takeIf { it > 0 } ?: allocateFreePort()
    val name = params.optString("name", "tcpserver").ifEmpty { "tcpserver" }

    val iface = TCPServerInterface(
        name = name,
        bindAddress = "127.0.0.1",
        bindPort = bindPort,
    )

    // Register each spawned child interface with Transport BEFORE start()
    // opens the accept loop. The parent TCPServerInterface's processOutgoing
    // is intentionally a no-op (post-#46) so that Transport routes outbound
    // packets via the spawned child that owns the actual socket. If the
    // spawned child isn't registered with Transport, findInterfaceByHash
    // returns null when an outbound link packet looks up its receiving
    // interface — and the packet is silently dropped. This manifests as
    // any DIRECT-from-this-bridge LXMF send appearing to "succeed" (link
    // handshake completes) while the receiver never sees the data packet.
    // Mirrors the equivalent wiring in Columba's NativeInterfaceFactory.kt
    // and reticulum-kt PR #47.
    iface.onClientConnected = { spawned ->
        runCatching {
            Transport.registerInterface(spawned.toRef())
        }.onFailure { e ->
            System.err.println(
                "[bridge] Failed to register spawned client ${spawned.name}: ${e.message}"
            )
        }
    }
    // Symmetric deregister so a long-running bridge with repeated
    // connect/disconnect cycles doesn't accumulate stale closed-socket
    // entries in Transport.interfaces. The upstream
    // TCPServerInterface.clientDisconnected (rns-interfaces v0.0.15+)
    // already invokes Transport.deregisterInterface internally on the
    // child it owns; this hook is a belt-and-suspenders second call to
    // the same API, idempotent if the child was already removed.
    iface.onClientDisconnected = { spawned ->
        runCatching {
            Transport.deregisterInterface(spawned.toRef())
        }
    }

    iface.start()
    Transport.registerInterface(iface.toRef())
    BridgeState.interfaces.add(iface)

    return JSONObject().put("port", bindPort).put("interface_name", name)
}

private fun cmdLxmfAddTcpClientInterface(params: JSONObject): JSONObject {
    ensureRouter("lxmf_add_tcp_client_interface")
    val targetHost = params.optString("target_host", "127.0.0.1").ifEmpty { "127.0.0.1" }
    val targetPort = params.getInt("target_port")
    val name = params.optString("name", "tcpclient").ifEmpty { "tcpclient" }

    val iface = TCPClientInterface(
        name = name,
        targetHost = targetHost,
        targetPort = targetPort,
    )
    iface.start()
    Transport.registerInterface(iface.toRef())
    BridgeState.interfaces.add(iface)

    return JSONObject().put("interface_name", name)
}

private fun cmdLxmfAnnounce(params: JSONObject): JSONObject {
    val router = ensureRouter("lxmf_announce")
    val dest = BridgeState.deliveryDestination
        ?: throw IllegalStateException("Delivery destination not registered")
    router.announce(dest)
    return JSONObject().put("delivery_destination_hash", dest.hash.toHexString())
}

private fun makeOutboundDelivery(destHashHex: String): Destination {
    val destHash = hexToBytes(destHashHex)
    val recipientIdentity = Identity.recall(destHash)
        ?: throw IllegalStateException(
            "No identity known for destination $destHashHex. The recipient " +
                "must announce its delivery destination before this peer can send to it."
        )
    return Destination.create(
        identity = recipientIdentity,
        direction = DestinationDirection.OUT,
        type = DestinationType.SINGLE,
        appName = "lxmf",
        "delivery",
    )
}

/**
 * Shared body for the three lxmf_send_* JSON-RPC commands. They differ
 * only in the DeliveryMethod enum value and the routerErrorTag used in
 * the not-yet-initialised error message. Keeping the shape in one place
 * means callback wiring, hash recording, and the
 * runBlocking-handleOutbound boundary can't drift between methods.
 */
private fun cmdLxmfSendCommon(
    params: JSONObject,
    method: DeliveryMethod,
    routerErrorTag: String,
): JSONObject {
    val router = ensureRouter(routerErrorTag)
    val source = BridgeState.deliveryDestination
        ?: throw IllegalStateException("source delivery destination not registered")

    val destHashHex = params.getString("destination_hash")
    val content = params.getString("content")
    val title = params.optString("title", "")

    val recipientDestination = makeOutboundDelivery(destHashHex)

    val message = LXMessage.create(
        destination = recipientDestination,
        source = source,
        content = content,
        title = title,
        fields = decodeFieldsParam(params),
        desiredMethod = method,
    )
    // Per-message callbacks so we can track state transitions.
    message.deliveryCallback = { m ->
        m.hash?.let { recordOutboundState(it.toHexString(), stateToString(m.state)) }
    }
    message.failedCallback = { m ->
        m.hash?.let { recordOutboundState(it.toHexString(), stateToString(m.state)) }
    }

    runBlocking { router.handleOutbound(message) }
    val msgHashHex = message.hash?.toHexString() ?: ""
    if (msgHashHex.isNotEmpty()) {
        recordOutboundState(msgHashHex, stateToString(message.state))
        // Keep a live reference so cmdLxmfGetMessageState can read the
        // current message.state directly. The router advances state
        // through transitions (OUTBOUND → SENT for opportunistic;
        // OUTBOUND → SENDING → SENT for propagated) without firing the
        // deliveryCallback for the intermediate ones, so polling
        // outboundState alone misses real progress.
        BridgeState.outboundMessages[msgHashHex] = message
    }

    return JSONObject().put("message_hash", msgHashHex)
}

private fun cmdLxmfSendOpportunistic(params: JSONObject): JSONObject =
    cmdLxmfSendCommon(params, DeliveryMethod.OPPORTUNISTIC, "lxmf_send_opportunistic")

private fun cmdLxmfSendDirect(params: JSONObject): JSONObject =
    cmdLxmfSendCommon(params, DeliveryMethod.DIRECT, "lxmf_send_direct")

// ----------------------------------------------------------------------
// Path probing
// ----------------------------------------------------------------------
//
// has_path requires BOTH Transport.hasPath() AND Identity.recall(). The
// LXMF send path needs the identity to encrypt the LXM, so a fixture
// that polls only on hasPath() can race past identity-recall and the
// next send fails. Mirrors the python bridge which made the same mistake
// once and got bitten — keep the AND-of-both contract identical.

private fun cmdLxmfHasPath(params: JSONObject): JSONObject {
    ensureRouter("lxmf_has_path")
    val destHash = hexToBytes(params.getString("destination_hash"))
    val transportHasPath = Transport.hasPath(destHash)
    val identityRecalled = Identity.recall(destHash) != null
    return JSONObject()
        .put("has_path", transportHasPath && identityRecalled)
        .put("transport_has_path", transportHasPath)
        .put("identity_recalled", identityRecalled)
}

private fun cmdLxmfRequestPath(params: JSONObject): JSONObject {
    ensureRouter("lxmf_request_path")
    val destHash = hexToBytes(params.getString("destination_hash"))
    Transport.requestPath(destHash)
    return JSONObject().put("requested", true)
}

// ----------------------------------------------------------------------
// Propagation
// ----------------------------------------------------------------------

private fun cmdLxmfSetOutboundPropagationNode(params: JSONObject): JSONObject {
    val router = ensureRouter("lxmf_set_outbound_propagation_node")
    val destHashHex = params.getString("destination_hash")
    router.setActivePropagationNode(destHashHex)
    return JSONObject().put("ok", true)
}

private fun cmdLxmfSendPropagated(params: JSONObject): JSONObject =
    cmdLxmfSendCommon(params, DeliveryMethod.PROPAGATED, "lxmf_send_propagated")

// Terminal states: COMPLETE, FAILED, NO_PATH, NO_LINK.
//
// IDLE is intentionally NOT in this set. IDLE is also the router's
// default resting state BEFORE a transfer begins, so if we read the
// state before requestMessagesFromPropagationNode() has had a chance
// to advance it past IDLE, we'd exit immediately and report
// "final_state=idle" without the transfer having run at all. We track
// "saw busy" separately and only treat IDLE as terminal once a busy
// state was observed.
private val TERMINAL_PROPAGATION_STATES = setOf(
    LXMRouter.PropagationTransferState.COMPLETE,
    LXMRouter.PropagationTransferState.FAILED,
    LXMRouter.PropagationTransferState.NO_PATH,
    LXMRouter.PropagationTransferState.NO_LINK,
)

private val BUSY_PROPAGATION_STATES = setOf(
    LXMRouter.PropagationTransferState.PATH_REQUESTED,
    LXMRouter.PropagationTransferState.LINK_ESTABLISHING,
    LXMRouter.PropagationTransferState.LINK_ESTABLISHED,
    LXMRouter.PropagationTransferState.LISTING_MESSAGES,
    LXMRouter.PropagationTransferState.REQUESTING_MESSAGES,
    LXMRouter.PropagationTransferState.RECEIVING_MESSAGES,
)

/**
 * Block until propagation sync is quiescent or the timeout expires.
 *
 * NOTE on the dispatch loop: this command is intentionally synchronous,
 * which means while we sleep/poll here the bridge's stdin dispatch loop
 * (`fun main()` while-loop) cannot service further commands until we
 * return. That's the contract — the conformance harness sends
 * `lxmf_sync_inbound` and waits for the result before proceeding, and
 * tests are sequenced one-command-at-a-time per bridge subprocess. If
 * the contract ever changes to allow concurrent commands while a sync
 * is in flight, this would need to dispatch the wait to a worker thread
 * and report completion via a separate poll command. For today's usage
 * the blocking shape is the right model.
 */
private fun cmdLxmfSyncInbound(params: JSONObject): JSONObject {
    val router = ensureRouter("lxmf_sync_inbound")
    val timeoutSec = params.optDouble("timeout_sec", 30.0)

    router.requestMessagesFromPropagationNode()

    val deadlineMs = System.currentTimeMillis() + (timeoutSec * 1000).toLong()
    var finalState = router.propagationTransferState
    var sawBusy = false
    while (System.currentTimeMillis() < deadlineMs) {
        finalState = router.propagationTransferState
        if (finalState in BUSY_PROPAGATION_STATES) {
            sawBusy = true
        }
        // Hard terminal: COMPLETE / FAILED / NO_PATH / NO_LINK — exit immediately.
        // Soft terminal: IDLE only counts after a busy state was seen, so we
        // don't bail on the pre-transfer resting state before the request has
        // had a chance to schedule any work.
        val terminalNow = finalState in TERMINAL_PROPAGATION_STATES ||
            (sawBusy && finalState == LXMRouter.PropagationTransferState.IDLE)
        if (terminalNow) {
            // Capture the terminal state BEFORE the settle. A COMPLETE
            // state normally cycles to IDLE during the brief settle
            // window; if we then re-read, we'd return "idle" and a
            // fixture that asserts "complete" would treat the sync as
            // never having started. Mirrors the python bridge's 0.5s
            // tail for in-flight observability without using the
            // post-settle value for the return.
            val terminalState = finalState
            Thread.sleep(500)
            return JSONObject().put("final_state", terminalState.name.lowercase())
        }
        Thread.sleep(200)
    }

    return JSONObject().put("final_state", finalState.name.lowercase())
}

private fun cmdLxmfGetReceivedMessages(params: JSONObject): JSONObject {
    ensureRouter("lxmf_get_received_messages")
    val sinceSeq = params.optInt("since_seq", 0)
    val out = JSONArray()
    val lastSeq: Int
    BridgeState.inboxLock.withLock {
        for (m in BridgeState.inbox) {
            if (m.getInt("seq") > sinceSeq) out.put(m)
        }
        lastSeq = BridgeState.inboxSeq
    }
    return JSONObject().put("messages", out).put("last_seq", lastSeq)
}

private fun cmdLxmfGetMessageState(params: JSONObject): JSONObject {
    ensureRouter("lxmf_get_message_state")
    val hashHex = params.getString("message_hash")
    val recordedState = BridgeState.outboundState[hashHex]

    // Prefer the recorded state when it's already terminal — those values
    // come from the actual deliveryCallback / failedCallback firings and
    // are authoritative. For non-terminal recorded states (or no record
    // at all), fall back to the live LXMessage's current state. The
    // router progresses messages through OUTBOUND → SENDING → SENT →
    // DELIVERED but only invokes deliveryCallback at terminal-for-method
    // (DELIVERED for opportunistic, SENT for propagated). The
    // intermediate transitions never reach the recorded map, so polling
    // it alone misses progress that already happened on the message.
    val state = if (recordedState in TERMINAL_OUTBOUND_STATES) {
        recordedState!!
    } else {
        val live = BridgeState.outboundMessages[hashHex]?.state
        if (live != null) stateToString(live) else (recordedState ?: "unknown")
    }
    return JSONObject().put("state", state)
}

/**
 * Decode raw LXMF wire bytes and return parsed components + computed hash.
 *
 * Byte-level conformance command. Does NOT require lxmf_init — operates
 * on the LXMessage decoder in isolation. The whole point is to exercise
 * the msgpack/payload parsing layer directly, against payload shapes
 * that may be impossible to elicit through normal send commands (e.g.
 * a fields slot encoded as msgpack Nil, which kotlin's own sender never
 * emits but iOS LXMF does — and which kotlin's decoder used to throw on,
 * silently dropping every iOS-originated message).
 *
 * Mirrors lxmf_python.py::cmd_lxmf_decode_bytes.
 *
 * Implements the same logic shape as LXMessage.unpackFromBytes (the very
 * code path under test) but without going through Identity recall /
 * signature validation, so test bytes can use a dummy signature and
 * unknown destination/source hashes.
 */
private fun cmdLxmfDecodeBytes(params: JSONObject): JSONObject {
    val DEST_LEN = 16
    val SIG_LEN = 64

    val lxmfBytesHex = params.optString("lxmf_bytes", "")
    val lxmfBytes = try {
        hexToBytes(lxmfBytesHex)
    } catch (e: Exception) {
        return JSONObject().put("decode_error", "hex parse: ${e::class.simpleName}: ${e.message}")
    }

    if (lxmfBytes.size < 2 * DEST_LEN + SIG_LEN) {
        return JSONObject().put("decode_error", "lxmf_bytes too short: ${lxmfBytes.size}")
    }

    // Call the production decoder directly. This is the WHOLE POINT of the
    // command — to exercise the actual LXMessage.unpackFromBytes code path
    // that runs in the wild, not a parallel re-implementation. A bridge
    // that re-implemented decode here would silently mask production
    // decoder bugs (e.g. the iOS-Nil-fields landmine that took weeks to
    // find precisely because the conformance suite couldn't reach the
    // production code path).
    val msg = network.reticulum.lxmf.LXMessage.unpackFromBytes(lxmfBytes)
        ?: return JSONObject().put(
            "decode_error",
            "LXMessage.unpackFromBytes returned null — see bridge stderr for the underlying exception"
        )

    // Detect whether the wire form had Nil fields by re-parsing just that
    // byte position. This is shape-level — production keeps fields as a
    // (possibly empty) Map; the wire-side Nil/Map distinction is only
    // load-bearing through the hash computation which production already
    // handles. For the test surface, expose it diagnostically.
    val packedPayload = lxmfBytes.copyOfRange(2 * DEST_LEN + SIG_LEN, lxmfBytes.size)
    val fieldsWasNil = try {
        val u = org.msgpack.core.MessagePack.newDefaultUnpacker(packedPayload)
        u.unpackArrayHeader()
        u.skipValue() // timestamp
        u.skipValue() // title
        u.skipValue() // content
        val isNil = u.nextFormat.valueType.name == "NIL"
        u.close()
        isNil
    } catch (_: Exception) {
        false
    }

    val title = msg.title
    val content = msg.content
    val titleHex = title.toByteArray(Charsets.UTF_8).toHexString()
    val contentHex = content.toByteArray(Charsets.UTF_8).toHexString()

    return JSONObject()
        .put("destination_hash", msg.destinationHash.toHexString())
        .put("source_hash", msg.sourceHash.toHexString())
        .put("signature", (msg.signature ?: ByteArray(0)).toHexString())
        .put("timestamp", msg.timestamp ?: 0.0)
        .put("title_hex", titleHex)
        .put("content_hex", contentHex)
        .put("fields_was_nil", fieldsWasNil)
        .put("fields_count", msg.fields.size)
        .put("stamp", msg.stamp?.toHexString() ?: JSONObject.NULL)
        .put("message_hash", (msg.hash ?: ByteArray(0)).toHexString())
}

private fun cmdLxmfShutdown(params: JSONObject): JSONObject {
    // Set the shuttingDown flag FIRST so any callbacks the router fires
    // during teardown can't repopulate cleared collections behind us.
    // The flag is checked by recordOutboundState() and the
    // registerDeliveryCallback closure.
    BridgeState.shuttingDown = true
    var stopped = false
    val router = BridgeState.router
    if (router != null) {
        try { router.stop() } catch (_: Throwable) {}
        BridgeState.router = null
        stopped = true
    }
    for (iface in BridgeState.interfaces) {
        try { iface.detach() } catch (_: Throwable) {}
    }
    BridgeState.interfaces.clear()
    try { Reticulum.stop() } catch (_: Throwable) {}
    BridgeState.reticulum = null
    BridgeState.identity = null
    BridgeState.deliveryDestination = null

    // Best-effort cleanup of tempdirs.
    // configDir is always auto-generated by lxmf_init, so always delete.
    // storagePath is only deleted when the bridge created it; a caller-
    // supplied path is left in place so a fixture that reuses storage
    // across multiple trios doesn't get its data wiped.
    if (BridgeState.storagePathAutoCreated) {
        BridgeState.storagePath?.let { runCatching { File(it).deleteRecursively() } }
    }
    BridgeState.configDir?.let { runCatching { File(it).deleteRecursively() } }
    BridgeState.storagePath = null
    BridgeState.storagePathAutoCreated = false
    BridgeState.configDir = null

    BridgeState.inboxLock.withLock {
        BridgeState.inbox.clear()
        BridgeState.inboxSeq = 0
    }
    BridgeState.outboundState.clear()
    BridgeState.outboundMessages.clear()

    return JSONObject().put("stopped", stopped)
}

// ----------------------------------------------------------------------
// Dispatch
// ----------------------------------------------------------------------

private val COMMANDS: Map<String, (JSONObject) -> JSONObject> = mapOf(
    "lxmf_init" to ::cmdLxmfInit,
    "lxmf_add_tcp_server_interface" to ::cmdLxmfAddTcpServerInterface,
    "lxmf_add_tcp_client_interface" to ::cmdLxmfAddTcpClientInterface,
    "lxmf_announce" to ::cmdLxmfAnnounce,
    "lxmf_send_opportunistic" to ::cmdLxmfSendOpportunistic,
    "lxmf_send_direct" to ::cmdLxmfSendDirect,
    "lxmf_send_propagated" to ::cmdLxmfSendPropagated,
    "lxmf_has_path" to ::cmdLxmfHasPath,
    "lxmf_request_path" to ::cmdLxmfRequestPath,
    "lxmf_set_outbound_propagation_node" to ::cmdLxmfSetOutboundPropagationNode,
    "lxmf_sync_inbound" to ::cmdLxmfSyncInbound,
    "lxmf_get_received_messages" to ::cmdLxmfGetReceivedMessages,
    "lxmf_get_message_state" to ::cmdLxmfGetMessageState,
    "lxmf_decode_bytes" to ::cmdLxmfDecodeBytes,
    "lxmf_shutdown" to ::cmdLxmfShutdown,
)

private fun handleRequest(line: String): JSONObject {
    val request: JSONObject = try {
        JSONObject(line)
    } catch (e: Exception) {
        return JSONObject()
            .put("id", "parse_error")
            .put("success", false)
            .put("error", "JSON parse: ${e.message}")
    }

    val reqId = request.optString("id", "")
    val command = request.optString("command", "")
    val params = request.optJSONObject("params") ?: JSONObject()

    val handler = COMMANDS[command]
        ?: return JSONObject()
            .put("id", reqId)
            .put("success", false)
            .put("error", "Unknown command: $command")

    return try {
        val result = handler(params)
        JSONObject().put("id", reqId).put("success", true).put("result", result)
    } catch (t: Throwable) {
        val sw = java.io.StringWriter()
        t.printStackTrace(java.io.PrintWriter(sw))
        JSONObject()
            .put("id", reqId)
            .put("success", false)
            .put("error", "${t.javaClass.simpleName}: ${t.message}\n$sw")
    }
}

private fun hexToBytes(hex: String): ByteArray {
    val clean = hex.lowercase()
    require(clean.length % 2 == 0) { "Invalid hex length: ${clean.length}" }
    require(clean.all { it in '0'..'9' || it in 'a'..'f' }) {
        "Invalid hex string: contains non-hex characters"
    }
    val out = ByteArray(clean.length / 2)
    for (i in out.indices) {
        out[i] = ((Character.digit(clean[i * 2], 16) shl 4) or
            Character.digit(clean[i * 2 + 1], 16)).toByte()
    }
    return out
}

fun main() {
    // Suppress slf4j-simple noise on stdout — stdout is the JSON-RPC channel.
    // Default level is INFO; bump to WARN. Direct slf4j-simple to stderr.
    System.setProperty("org.slf4j.simpleLogger.defaultLogLevel", "warn")
    System.setProperty("org.slf4j.simpleLogger.logFile", "System.err")

    // Capture original stdout / stderr by reference. Using these
    // references for the JSON-RPC channel and for the redirect target
    // keeps both stable even if a future test framework swaps the
    // System.out / System.err globals out from under us.
    val out = System.out
    val err = System.err
    val reader = BufferedReader(InputStreamReader(System.`in`))

    out.println("READY")
    out.flush()

    // After READY, hijack System.out and route subsequent stdout writes
    // to stderr. The JSON-RPC channel uses the captured `out` directly,
    // so this only redirects unstructured prints. Without this, every
    // `println(...)` in lxmf-kt / reticulum-kt leaks onto the response
    // channel and the test harness silently drops it as non-JSON, so
    // bugs in the underlying stack are completely invisible to anyone
    // running the conformance suite. We point to the captured `err`
    // reference so a future System.err swap doesn't redirect us
    // somewhere unexpected.
    System.setOut(err)

    while (true) {
        val line = try { reader.readLine() } catch (e: Exception) { null }
        if (line == null) break
        val trimmed = line.trim()
        if (trimmed.isEmpty()) continue
        val response = handleRequest(trimmed)
        out.println(response.toString())
        out.flush()
    }
    exitProcess(0)
}
